module.exports = {
 SPX: [{"Symbol":"AAPL","Sector":"Information Technology"},
{"Symbol":"MSFT","Sector":"Information Technology"},
{"Symbol":"XOM","Sector":"Energy"},
{"Symbol":"JNJ","Sector":"Health Care"},
{"Symbol":"GE","Sector":"Industrials"},
{"Symbol":"FB","Sector":"Information Technology"},
{"Symbol":"T","Sector":"Telecommunication Services"},
{"Symbol":"WFC","Sector":"Financials"},
{"Symbol":"PG","Sector":"Consumer Staples"},
{"Symbol":"AMZN","Sector":"Consumer Discretionary"},
{"Symbol":"JPM","Sector":"Financials"},
{"Symbol":"GOOGL","Sector":"Information Technology"},
{"Symbol":"GOOG","Sector":"Information Technology"},
{"Symbol":"VZ","Sector":"Telecommunication Services"},
{"Symbol":"PFE","Sector":"Health Care"},
{"Symbol":"CVX","Sector":"Energy"},
{"Symbol":"KO","Sector":"Consumer Staples"},
{"Symbol":"HD","Sector":"Consumer Discretionary"},
{"Symbol":"INTC","Sector":"Information Technology"},
{"Symbol":"PM","Sector":"Consumer Staples"},
{"Symbol":"DIS","Sector":"Consumer Discretionary"},
{"Symbol":"MRK","Sector":"Health Care"},
{"Symbol":"PEP","Sector":"Consumer Staples"},
{"Symbol":"CMCSA","Sector":"Consumer Discretionary"},
{"Symbol":"BAC","Sector":"Financials"},
{"Symbol":"CSCO","Sector":"Information Technology"},
{"Symbol":"V","Sector":"Information Technology"},
{"Symbol":"C","Sector":"Financials"},
{"Symbol":"IBM","Sector":"Information Technology"},
{"Symbol":"ORCL","Sector":"Information Technology"},
{"Symbol":"GILD","Sector":"Health Care"},
{"Symbol":"MO","Sector":"Consumer Staples"},
{"Symbol":"UNH","Sector":"Health Care"},
{"Symbol":"AGN","Sector":"Health Care"},
{"Symbol":"MCD","Sector":"Consumer Discretionary"},
{"Symbol":"CVS","Sector":"Consumer Staples"},
{"Symbol":"AMGN","Sector":"Health Care"},
{"Symbol":"MDT","Sector":"Health Care"},
{"Symbol":"BMY","Sector":"Health Care"},
{"Symbol":"WMT","Sector":"Consumer Staples"},
{"Symbol":"MMM","Sector":"Industrials"},
{"Symbol":"SLB","Sector":"Energy"},
{"Symbol":"ABBV","Sector":"Health Care"},
{"Symbol":"MA","Sector":"Information Technology"},
{"Symbol":"SBUX","Sector":"Consumer Discretionary"},
{"Symbol":"HON","Sector":"Industrials"},
{"Symbol":"NKE","Sector":"Consumer Discretionary"},
{"Symbol":"CELG","Sector":"Health Care"},
{"Symbol":"BA","Sector":"Industrials"},
{"Symbol":"QCOM","Sector":"Information Technology"},
{"Symbol":"UTX","Sector":"Industrials"},
{"Symbol":"LLY","Sector":"Health Care"},
{"Symbol":"WBA","Sector":"Consumer Staples"},
{"Symbol":"UPS","Sector":"Industrials"},
{"Symbol":"UNP","Sector":"Industrials"},
{"Symbol":"MDLZ","Sector":"Consumer Staples"},
{"Symbol":"COST","Sector":"Consumer Staples"},
{"Symbol":"USB","Sector":"Financials"},
{"Symbol":"ACN","Sector":"Information Technology"},
{"Symbol":"PCLN","Sector":"Consumer Discretionary"},
{"Symbol":"LOW","Sector":"Consumer Discretionary"},
{"Symbol":"SPG","Sector":"Financials"},
{"Symbol":"CL","Sector":"Consumer Staples"},
{"Symbol":"GS","Sector":"Financials"},
{"Symbol":"AIG","Sector":"Financials"},
{"Symbol":"ABT","Sector":"Health Care"},
{"Symbol":"BIIB","Sector":"Health Care"},
{"Symbol":"AVGO","Sector":"Information Technology"},
{"Symbol":"LMT","Sector":"Industrials"},
{"Symbol":"DOW","Sector":"Materials"},
{"Symbol":"TXN","Sector":"Information Technology"},
{"Symbol":"TWX","Sector":"Consumer Discretionary"},
{"Symbol":"TMO","Sector":"Health Care"},
{"Symbol":"DD","Sector":"Materials"},
{"Symbol":"TWC","Sector":"Consumer Discretionary"},
{"Symbol":"CB","Sector":"Financials"},
{"Symbol":"DHR","Sector":"Industrials"},
{"Symbol":"DUK","Sector":"Utilities"},
{"Symbol":"OXY","Sector":"Energy"},
{"Symbol":"NEE","Sector":"Utilities"},
{"Symbol":"F","Sector":"Consumer Discretionary"},
{"Symbol":"EMC","Sector":"Information Technology"},
{"Symbol":"TJX","Sector":"Consumer Discretionary"},
{"Symbol":"TGT","Sector":"Consumer Discretionary"},
{"Symbol":"COP","Sector":"Energy"},
{"Symbol":"AXP","Sector":"Financials"},
{"Symbol":"MET","Sector":"Financials"},
{"Symbol":"KMB","Sector":"Consumer Staples"},
{"Symbol":"ESRX","Sector":"Health Care"},
{"Symbol":"KHC","Sector":"Consumer Staples"},
{"Symbol":"SO","Sector":"Utilities"},
{"Symbol":"CRM","Sector":"Information Technology"},
{"Symbol":"GM","Sector":"Consumer Discretionary"},
{"Symbol":"PYPL","Sector":"Information Technology"},
{"Symbol":"PNC","Sector":"Financials"},
{"Symbol":"D","Sector":"Utilities"},
{"Symbol":"ADBE","Sector":"Information Technology"},
{"Symbol":"BLK","Sector":"Financials"},
{"Symbol":"CAT","Sector":"Industrials"},
{"Symbol":"RAI","Sector":"Consumer Staples"},
{"Symbol":"NFLX","Sector":"Consumer Discretionary"},
{"Symbol":"AMT","Sector":"Financials"},
{"Symbol":"EOG","Sector":"Energy"},
{"Symbol":"BK","Sector":"Financials"},
{"Symbol":"PSX","Sector":"Energy"},
{"Symbol":"GD","Sector":"Industrials"},
{"Symbol":"ADP","Sector":"Information Technology"},
{"Symbol":"MON","Sector":"Materials"},
{"Symbol":"AET","Sector":"Health Care"},
{"Symbol":"MS","Sector":"Financials"},
{"Symbol":"MCK","Sector":"Health Care"},
{"Symbol":"PSA","Sector":"Financials"},
{"Symbol":"COF","Sector":"Financials"},
{"Symbol":"FDX","Sector":"Industrials"},
{"Symbol":"DAL","Sector":"Industrials"},
{"Symbol":"KR","Sector":"Consumer Staples"},
{"Symbol":"CI","Sector":"Health Care"},
{"Symbol":"ANTM","Sector":"Health Care"},
{"Symbol":"RTN","Sector":"Industrials"},
{"Symbol":"GIS","Sector":"Consumer Staples"},
{"Symbol":"CTSH","Sector":"Information Technology"},
{"Symbol":"NOC","Sector":"Industrials"},
{"Symbol":"TRV","Sector":"Financials"},
{"Symbol":"KMI","Sector":"Energy"},
{"Symbol":"SCHW","Sector":"Financials"},
{"Symbol":"EMR","Sector":"Industrials"},
{"Symbol":"SYK","Sector":"Health Care"},
{"Symbol":"PRU","Sector":"Financials"},
{"Symbol":"FOXA","Sector":"Consumer Discretionary"},
{"Symbol":"ITW","Sector":"Industrials"},
{"Symbol":"CME","Sector":"Financials"},
{"Symbol":"YUM","Sector":"Consumer Discretionary"},
{"Symbol":"EXC","Sector":"Utilities"},
{"Symbol":"PX","Sector":"Materials"},
{"Symbol":"BDX","Sector":"Health Care"},
{"Symbol":"AEP","Sector":"Utilities"},
{"Symbol":"VLO","Sector":"Energy"},
{"Symbol":"LYB","Sector":"Materials"},
{"Symbol":"ALXN","Sector":"Health Care"},
{"Symbol":"HAL","Sector":"Energy"},
{"Symbol":"MMC","Sector":"Financials"},
{"Symbol":"YHOO","Sector":"Information Technology"},
{"Symbol":"HPE","Sector":"Information Technology"},
{"Symbol":"REGN","Sector":"Health Care"},
{"Symbol":"CCI","Sector":"Financials"},
{"Symbol":"PPG","Sector":"Materials"},
{"Symbol":"ECL","Sector":"Materials"},
{"Symbol":"PCG","Sector":"Utilities"},
{"Symbol":"LUV","Sector":"Industrials"},
{"Symbol":"ICE","Sector":"Financials"},
{"Symbol":"ETN","Sector":"Industrials"},
{"Symbol":"HUM","Sector":"Health Care"},
{"Symbol":"CAH","Sector":"Health Care"},
{"Symbol":"AON","Sector":"Financials"},
{"Symbol":"ORLY","Sector":"Consumer Discretionary"},
{"Symbol":"BBT","Sector":"Financials"},
{"Symbol":"AFL","Sector":"Financials"},
{"Symbol":"AAL","Sector":"Industrials"},
{"Symbol":"EQR","Sector":"Financials"},
{"Symbol":"EBAY","Sector":"Information Technology"},
{"Symbol":"APD","Sector":"Materials"},
{"Symbol":"INTU","Sector":"Information Technology"},
{"Symbol":"DE","Sector":"Industrials"},
{"Symbol":"MHFI","Sector":"Financials"},
{"Symbol":"CSX","Sector":"Industrials"},
{"Symbol":"ALL","Sector":"Financials"},
{"Symbol":"AVB","Sector":"Financials"},
{"Symbol":"DG","Sector":"Consumer Discretionary"},
{"Symbol":"STZ","Sector":"Consumer Staples"},
{"Symbol":"PPL","Sector":"Utilities"},
{"Symbol":"AZO","Sector":"Consumer Discretionary"},
{"Symbol":"BSX","Sector":"Health Care"},
{"Symbol":"JCI","Sector":"Consumer Discretionary"},
{"Symbol":"WM","Sector":"Industrials"},
{"Symbol":"SYF","Sector":"Financials"},
{"Symbol":"SYY","Sector":"Consumer Staples"},
{"Symbol":"NSC","Sector":"Industrials"},
{"Symbol":"HCN","Sector":"Financials"},
{"Symbol":"HCA","Sector":"Health Care"},
{"Symbol":"ROST","Sector":"Consumer Discretionary"},
{"Symbol":"STT","Sector":"Financials"},
{"Symbol":"APC","Sector":"Energy"},
{"Symbol":"SRE","Sector":"Utilities"},
{"Symbol":"ILMN","Sector":"Health Care"},
{"Symbol":"TEL","Sector":"Information Technology"},
{"Symbol":"CBS","Sector":"Consumer Discretionary"},
{"Symbol":"AMAT","Sector":"Information Technology"},
{"Symbol":"BXLT","Sector":"Health Care"},
{"Symbol":"EIX","Sector":"Utilities"},
{"Symbol":"WY","Sector":"Financials"},
{"Symbol":"VFC","Sector":"Consumer Discretionary"},
{"Symbol":"PEG","Sector":"Utilities"},
{"Symbol":"SHW","Sector":"Materials"},
{"Symbol":"FISV","Sector":"Information Technology"},
{"Symbol":"PLD","Sector":"Financials"},
{"Symbol":"PXD","Sector":"Energy"},
{"Symbol":"CCL","Sector":"Consumer Discretionary"},
{"Symbol":"LB","Sector":"Consumer Discretionary"},
{"Symbol":"BAX","Sector":"Health Care"},
{"Symbol":"ADM","Sector":"Consumer Staples"},
{"Symbol":"UAL","Sector":"Industrials"},
{"Symbol":"EQIX","Sector":"Financials"},
{"Symbol":"ISRG","Sector":"Health Care"},
{"Symbol":"GLW","Sector":"Information Technology"},
{"Symbol":"ED","Sector":"Utilities"},
{"Symbol":"VRTX","Sector":"Health Care"},
{"Symbol":"HPQ","Sector":"Information Technology"},
{"Symbol":"DFS","Sector":"Financials"},
{"Symbol":"EL","Sector":"Consumer Staples"},
{"Symbol":"SE","Sector":"Energy"},
{"Symbol":"XEL","Sector":"Utilities"},
{"Symbol":"MPC","Sector":"Energy"},
{"Symbol":"MYL","Sector":"Health Care"},
{"Symbol":"EA","Sector":"Information Technology"},
{"Symbol":"MNST","Sector":"Consumer Staples"},
{"Symbol":"TSN","Sector":"Consumer Staples"},
{"Symbol":"PRGO","Sector":"Health Care"},
{"Symbol":"VTR","Sector":"Financials"},
{"Symbol":"BHI","Sector":"Energy"},
{"Symbol":"DLPH","Sector":"Consumer Discretionary"},
{"Symbol":"PGR","Sector":"Financials"},
{"Symbol":"K","Sector":"Consumer Staples"},
{"Symbol":"OMC","Sector":"Consumer Discretionary"},
{"Symbol":"ZTS","Sector":"Health Care"},
{"Symbol":"CAG","Sector":"Consumer Staples"},
{"Symbol":"STI","Sector":"Financials"},
{"Symbol":"ZBH","Sector":"Health Care"},
{"Symbol":"DLTR","Sector":"Consumer Discretionary"},
{"Symbol":"EW","Sector":"Health Care"},
{"Symbol":"BXP","Sector":"Financials"},
{"Symbol":"APA","Sector":"Energy"},
{"Symbol":"NLSN","Sector":"Industrials"},
{"Symbol":"PCAR","Sector":"Industrials"},
{"Symbol":"HIG","Sector":"Financials"},
{"Symbol":"TROW","Sector":"Financials"},
{"Symbol":"WEC","Sector":"Utilities"},
{"Symbol":"ES","Sector":"Utilities"},
{"Symbol":"MTB","Sector":"Financials"},
{"Symbol":"ROP","Sector":"Industrials"},
{"Symbol":"CTL","Sector":"Telecommunication Services"},
{"Symbol":"ABC","Sector":"Health Care"},
{"Symbol":"FIS","Sector":"Information Technology"},
{"Symbol":"ADI","Sector":"Information Technology"},
{"Symbol":"DPS","Sector":"Consumer Staples"},
{"Symbol":"APH","Sector":"Information Technology"},
{"Symbol":"CMI","Sector":"Industrials"},
{"Symbol":"PAYX","Sector":"Information Technology"},
{"Symbol":"TAP","Sector":"Consumer Staples"},
{"Symbol":"GGP","Sector":"Financials"},
{"Symbol":"WLTW","Sector":"Financials"},
{"Symbol":"IP","Sector":"Materials"},
{"Symbol":"CERN","Sector":"Health Care"},
{"Symbol":"NVDA","Sector":"Information Technology"},
{"Symbol":"MCO","Sector":"Financials"},
{"Symbol":"VNO","Sector":"Financials"},
{"Symbol":"CLX","Sector":"Consumer Staples"},
{"Symbol":"AMP","Sector":"Financials"},
{"Symbol":"STJ","Sector":"Health Care"},
{"Symbol":"CMG","Sector":"Consumer Discretionary"},
{"Symbol":"ATVI","Sector":"Information Technology"},
{"Symbol":"DTE","Sector":"Utilities"},
{"Symbol":"SNDK","Sector":"Information Technology"},
{"Symbol":"SJM","Sector":"Consumer Staples"},
{"Symbol":"IR","Sector":"Industrials"},
{"Symbol":"XRAY","Sector":"Health Care"},
{"Symbol":"HCP","Sector":"Financials"},
{"Symbol":"TYC","Sector":"Industrials"},
{"Symbol":"FE","Sector":"Utilities"},
{"Symbol":"SWK","Sector":"Industrials"},
{"Symbol":"LVLT","Sector":"Telecommunication Services"},
{"Symbol":"UA","Sector":"Consumer Discretionary"},
{"Symbol":"O","Sector":"Financials"},
{"Symbol":"PH","Sector":"Industrials"},
{"Symbol":"ESS","Sector":"Financials"},
{"Symbol":"BEN","Sector":"Financials"},
{"Symbol":"GPC","Sector":"Consumer Discretionary"},
{"Symbol":"NUE","Sector":"Materials"},
{"Symbol":"BCR","Sector":"Health Care"},
{"Symbol":"NTRS","Sector":"Financials"},
{"Symbol":"NBL","Sector":"Energy"},
{"Symbol":"HSIC","Sector":"Health Care"},
{"Symbol":"ROK","Sector":"Industrials"},
{"Symbol":"MJN","Sector":"Consumer Staples"},
{"Symbol":"NEM","Sector":"Materials"},
{"Symbol":"M","Sector":"Consumer Discretionary"},
{"Symbol":"FITB","Sector":"Financials"},
{"Symbol":"SWKS","Sector":"Information Technology"},
{"Symbol":"VMC","Sector":"Materials"},
{"Symbol":"VIAB","Sector":"Consumer Discretionary"},
{"Symbol":"FAST","Sector":"Industrials"},
{"Symbol":"ETR","Sector":"Utilities"},
{"Symbol":"HES","Sector":"Energy"},
{"Symbol":"EXPE","Sector":"Consumer Discretionary"},
{"Symbol":"HSY","Sector":"Consumer Staples"},
{"Symbol":"MAR","Sector":"Consumer Discretionary"},
{"Symbol":"CXO","Sector":"Energy"},
{"Symbol":"A","Sector":"Health Care"},
{"Symbol":"RHT","Sector":"Information Technology"},
{"Symbol":"ADS","Sector":"Information Technology"},
{"Symbol":"CAM","Sector":"Energy"},
{"Symbol":"EFX","Sector":"Industrials"},
{"Symbol":"WHR","Sector":"Consumer Discretionary"},
{"Symbol":"IVZ","Sector":"Financials"},
{"Symbol":"ADSK","Sector":"Information Technology"},
{"Symbol":"DVN","Sector":"Energy"},
{"Symbol":"GWW","Sector":"Industrials"},
{"Symbol":"NOV","Sector":"Energy"},
{"Symbol":"RCL","Sector":"Consumer Discretionary"},
{"Symbol":"SYMC","Sector":"Information Technology"},
{"Symbol":"MU","Sector":"Information Technology"},
{"Symbol":"AA","Sector":"Materials"},
{"Symbol":"HST","Sector":"Financials"},
{"Symbol":"AWK","Sector":"Utilities"},
{"Symbol":"TSCO","Sector":"Consumer Discretionary"},
{"Symbol":"FOX","Sector":"Consumer Discretionary"},
{"Symbol":"XLNX","Sector":"Information Technology"},
{"Symbol":"HOT","Sector":"Consumer Discretionary"},
{"Symbol":"LRCX","Sector":"Information Technology"},
{"Symbol":"FCX","Sector":"Materials"},
{"Symbol":"DVA","Sector":"Health Care"},
{"Symbol":"COL","Sector":"Industrials"},
{"Symbol":"HRL","Sector":"Consumer Staples"},
{"Symbol":"CHD","Sector":"Consumer Staples"},
{"Symbol":"VRSK","Sector":"Industrials"},
{"Symbol":"CTXS","Sector":"Information Technology"},
{"Symbol":"AEE","Sector":"Utilities"},
{"Symbol":"MHK","Sector":"Consumer Discretionary"},
{"Symbol":"LH","Sector":"Health Care"},
{"Symbol":"CFG","Sector":"Financials"},
{"Symbol":"AAP","Sector":"Consumer Discretionary"},
{"Symbol":"HBI","Sector":"Consumer Discretionary"},
{"Symbol":"MSI","Sector":"Information Technology"},
{"Symbol":"WDC","Sector":"Information Technology"},
{"Symbol":"AME","Sector":"Industrials"},
{"Symbol":"KIM","Sector":"Financials"},
{"Symbol":"RSG","Sector":"Industrials"},
{"Symbol":"WFM","Sector":"Consumer Staples"},
{"Symbol":"CPB","Sector":"Consumer Staples"},
{"Symbol":"CMS","Sector":"Utilities"},
{"Symbol":"COH","Sector":"Consumer Discretionary"},
{"Symbol":"NWL","Sector":"Consumer Discretionary"},
{"Symbol":"MAT","Sector":"Consumer Discretionary"},
{"Symbol":"PFG","Sector":"Financials"},
{"Symbol":"WMB","Sector":"Energy"},
{"Symbol":"STX","Sector":"Information Technology"},
{"Symbol":"MKC","Sector":"Consumer Staples"},
{"Symbol":"KORS","Sector":"Consumer Discretionary"},
{"Symbol":"KLAC","Sector":"Information Technology"},
{"Symbol":"RF","Sector":"Financials"},
{"Symbol":"TSO","Sector":"Energy"},
{"Symbol":"MAC","Sector":"Financials"},
{"Symbol":"XL","Sector":"Financials"},
{"Symbol":"EXR","Sector":"Financials"},
{"Symbol":"WAT","Sector":"Health Care"},
{"Symbol":"FRT","Sector":"Financials"},
{"Symbol":"L","Sector":"Financials"},
{"Symbol":"CCE","Sector":"Consumer Staples"},
{"Symbol":"LLTC","Sector":"Information Technology"},
{"Symbol":"KMX","Sector":"Consumer Discretionary"},
{"Symbol":"EMN","Sector":"Materials"},
{"Symbol":"UHS","Sector":"Health Care"},
{"Symbol":"MLM","Sector":"Materials"},
{"Symbol":"CHRW","Sector":"Industrials"},
{"Symbol":"XRX","Sector":"Information Technology"},
{"Symbol":"BBY","Sector":"Consumer Discretionary"},
{"Symbol":"DGX","Sector":"Health Care"},
{"Symbol":"COG","Sector":"Energy"},
{"Symbol":"HRS","Sector":"Information Technology"},
{"Symbol":"MAS","Sector":"Industrials"},
{"Symbol":"AKAM","Sector":"Information Technology"},
{"Symbol":"LNC","Sector":"Financials"},
{"Symbol":"MCHP","Sector":"Information Technology"},
{"Symbol":"DOV","Sector":"Industrials"},
{"Symbol":"SRCL","Sector":"Industrials"},
{"Symbol":"WU","Sector":"Information Technology"},
{"Symbol":"DHI","Sector":"Consumer Discretionary"},
{"Symbol":"MOS","Sector":"Materials"},
{"Symbol":"WRK","Sector":"Materials"},
{"Symbol":"UDR","Sector":"Financials"},
{"Symbol":"CINF","Sector":"Financials"},
{"Symbol":"SCG","Sector":"Utilities"},
{"Symbol":"BLL","Sector":"Materials"},
{"Symbol":"HOG","Sector":"Consumer Discretionary"},
{"Symbol":"SLG","Sector":"Financials"},
{"Symbol":"KEY","Sector":"Financials"},
{"Symbol":"LLL","Sector":"Industrials"},
{"Symbol":"TXT","Sector":"Industrials"},
{"Symbol":"KSS","Sector":"Consumer Discretionary"},
{"Symbol":"SEE","Sector":"Materials"},
{"Symbol":"KSU","Sector":"Industrials"},
{"Symbol":"JNPR","Sector":"Information Technology"},
{"Symbol":"MRO","Sector":"Energy"},
{"Symbol":"ARG","Sector":"Materials"},
{"Symbol":"EQT","Sector":"Energy"},
{"Symbol":"PNR","Sector":"Industrials"},
{"Symbol":"EXPD","Sector":"Industrials"},
{"Symbol":"CA","Sector":"Information Technology"},
{"Symbol":"GT","Sector":"Consumer Discretionary"},
{"Symbol":"SIG","Sector":"Consumer Discretionary"},
{"Symbol":"CPGX","Sector":"Energy"},
{"Symbol":"WYN","Sector":"Consumer Discretionary"},
{"Symbol":"HAS","Sector":"Consumer Discretionary"},
{"Symbol":"ENDP","Sector":"Health Care"},
{"Symbol":"IFF","Sector":"Materials"},
{"Symbol":"XEC","Sector":"Energy"},
{"Symbol":"SNA","Sector":"Industrials"},
{"Symbol":"IPG","Sector":"Consumer Discretionary"},
{"Symbol":"VRSN","Sector":"Information Technology"},
{"Symbol":"CNP","Sector":"Utilities"},
{"Symbol":"BBBY","Sector":"Consumer Discretionary"},
{"Symbol":"AMG","Sector":"Financials"},
{"Symbol":"LEN","Sector":"Consumer Discretionary"},
{"Symbol":"CF","Sector":"Materials"},
{"Symbol":"BWA","Sector":"Consumer Discretionary"},
{"Symbol":"TIF","Sector":"Consumer Discretionary"},
{"Symbol":"CBG","Sector":"Financials"},
{"Symbol":"NTAP","Sector":"Information Technology"},
{"Symbol":"MNK","Sector":"Health Care"},
{"Symbol":"HBAN","Sector":"Financials"},
{"Symbol":"CTAS","Sector":"Industrials"},
{"Symbol":"GAS","Sector":"Utilities"},
{"Symbol":"UNM","Sector":"Financials"},
{"Symbol":"VAR","Sector":"Health Care"},
{"Symbol":"JWN","Sector":"Consumer Discretionary"},
{"Symbol":"PNW","Sector":"Utilities"},
{"Symbol":"DRI","Sector":"Consumer Discretionary"},
{"Symbol":"NDAQ","Sector":"Financials"},
{"Symbol":"TSS","Sector":"Information Technology"},
{"Symbol":"JBHT","Sector":"Industrials"},
{"Symbol":"AES","Sector":"Utilities"},
{"Symbol":"ETFC","Sector":"Financials"},
{"Symbol":"FLR","Sector":"Industrials"},
{"Symbol":"CVC","Sector":"Consumer Discretionary"},
{"Symbol":"NI","Sector":"Utilities"},
{"Symbol":"FFIV","Sector":"Information Technology"},
{"Symbol":"PVH","Sector":"Consumer Discretionary"},
{"Symbol":"TRIP","Sector":"Consumer Discretionary"},
{"Symbol":"DISCK","Sector":"Consumer Discretionary"},
{"Symbol":"XYL","Sector":"Industrials"},
{"Symbol":"GPS","Sector":"Consumer Discretionary"},
{"Symbol":"WYNN","Sector":"Consumer Discretionary"},
{"Symbol":"ADT","Sector":"Industrials"},
{"Symbol":"HP","Sector":"Energy"},
{"Symbol":"CMA","Sector":"Financials"},
{"Symbol":"HRB","Sector":"Consumer Discretionary"},
{"Symbol":"TMK","Sector":"Financials"},
{"Symbol":"TE","Sector":"Utilities"},
{"Symbol":"AVY","Sector":"Materials"},
{"Symbol":"QRVO","Sector":"Information Technology"},
{"Symbol":"FTI","Sector":"Energy"},
{"Symbol":"LEG","Sector":"Consumer Discretionary"},
{"Symbol":"SPLS","Sector":"Consumer Discretionary"},
{"Symbol":"FTR","Sector":"Telecommunication Services"},
{"Symbol":"AIV","Sector":"Financials"},
{"Symbol":"IRM","Sector":"Financials"},
{"Symbol":"SNI","Sector":"Consumer Discretionary"},
{"Symbol":"ALLE","Sector":"Industrials"},
{"Symbol":"FLS","Sector":"Industrials"},
{"Symbol":"PHM","Sector":"Consumer Discretionary"},
{"Symbol":"OKE","Sector":"Energy"},
{"Symbol":"RL","Sector":"Consumer Discretionary"},
{"Symbol":"HAR","Sector":"Consumer Discretionary"},
{"Symbol":"RHI","Sector":"Industrials"},
{"Symbol":"URI","Sector":"Industrials"},
{"Symbol":"POM","Sector":"Utilities"},
{"Symbol":"TGNA","Sector":"Consumer Discretionary"},
{"Symbol":"PKI","Sector":"Health Care"},
{"Symbol":"FMC","Sector":"Materials"},
{"Symbol":"FSLR","Sector":"Information Technology"},
{"Symbol":"RRC","Sector":"Energy"},
{"Symbol":"AIZ","Sector":"Financials"},
{"Symbol":"JEC","Sector":"Industrials"},
{"Symbol":"LUK","Sector":"Financials"},
{"Symbol":"NFX","Sector":"Energy"},
{"Symbol":"ZION","Sector":"Financials"},
{"Symbol":"PBCT","Sector":"Financials"},
{"Symbol":"GRMN","Sector":"Consumer Discretionary"},
{"Symbol":"FLIR","Sector":"Information Technology"},
{"Symbol":"NWSA","Sector":"Consumer Discretionary"},
{"Symbol":"NAVI","Sector":"Financials"},
{"Symbol":"NRG","Sector":"Utilities"},
{"Symbol":"DISCA","Sector":"Consumer Discretionary"},
{"Symbol":"PBI","Sector":"Industrials"},
{"Symbol":"AN","Sector":"Consumer Discretionary"},
{"Symbol":"MUR","Sector":"Energy"},
{"Symbol":"RIG","Sector":"Energy"},
{"Symbol":"PWR","Sector":"Industrials"},
{"Symbol":"PDCO","Sector":"Health Care"},
{"Symbol":"LM","Sector":"Financials"},
{"Symbol":"TDC","Sector":"Information Technology"},
{"Symbol":"DNB","Sector":"Industrials"},
{"Symbol":"CSRA","Sector":"Information Technology"},
{"Symbol":"GME","Sector":"Consumer Discretionary"},
{"Symbol":"R","Sector":"Industrials"},
{"Symbol":"SWN","Sector":"Energy"},
{"Symbol":"URBN","Sector":"Consumer Discretionary"},
{"Symbol":"THC","Sector":"Health Care"},
{"Symbol":"ESV","Sector":"Energy"},
{"Symbol":"CHK","Sector":"Energy"},
{"Symbol":"OI","Sector":"Materials"},
{"Symbol":"DO","Sector":"Energy"},
{"Symbol":"NWS","Sector":"Consumer Discretionary"},
{"Symbol":"GMCR","Sector":"Consumer Staples"}]
};


// ["AAPL", "MSFT", "XOM", "JNJ", "GE", "FB", "T", "WFC", "PG", "AMZN", "JPM", "GOOGL", "GOOG", "VZ", "PFE", "CVX", "KO", "HD", "INTC", "PM", "DIS", "MRK", "PEP", "CMCSA", "BAC", "CSCO", "V", "C", "IBM", "ORCL", "GILD", "MO", "UNH", "AGN", "MCD", "CVS", "AMGN", "MDT", "BMY", "WMT", "MMM", "SLB", "ABBV", "MA", "SBUX", "HON", "NKE", "CELG", "BA", "QCOM", "UTX", "LLY", "WBA", "UPS", "UNP", "MDLZ", "COST", "USB", "ACN", "PCLN", "LOW", "SPG", "CL", "GS", "AIG", "ABT", "BIIB", "AVGO", "LMT", "DOW", "TXN", "TWX", "TMO", "DD", "TWC", "CB", "DHR", "DUK", "OXY", "NEE", "F", "EMC", "TJX", "TGT", "COP", "AXP", "MET", "KMB", "ESRX", "KHC", "SO", "CRM", "GM", "PYPL", "PNC", "D", "ADBE", "BLK", "CAT", "RAI", "NFLX", "AMT", "EOG", "BK", "PSX", "GD", "ADP", "MON", "AET", "MS", "MCK", "PSA", "COF", "FDX", "DAL", "KR", "CI", "ANTM", "RTN", "GIS", "CTSH", "NOC", "TRV", "KMI", "SCHW", "EMR", "SYK", "PRU", "FOXA", "ITW", "CME", "YUM", "EXC", "PX", "BDX", "AEP", "VLO", "LYB", "ALXN", "HAL", "MMC", "YHOO", "HPE", "REGN", "CCI", "PPG", "ECL", "PCG", "LUV", "ICE", "ETN", "HUM", "CAH", "AON", "ORLY", "BBT", "AFL", "AAL", "EQR", "EBAY", "APD", "INTU", "DE", "MHFI", "CSX", "ALL", "AVB", "DG", "STZ", "PPL", "AZO", "BSX", "JCI", "WM", "SYF", "SYY", "NSC", "HCN", "HCA", "ROST", "STT", "APC", "SRE", "ILMN", "TEL", "CBS", "AMAT", "BXLT", "EIX", "WY", "VFC", "PEG", "SHW", "FISV", "PLD", "PXD", "CCL", "LB", "BAX", "ADM", "UAL", "EQIX", "ISRG", "GLW", "ED", "VRTX", "HPQ", "DFS", "EL", "SE", "XEL", "MPC", "MYL", "EA", "MNST", "TSN", "PRGO", "VTR", "BHI", "DLPH", "PGR", "K", "OMC", "ZTS", "CAG", "STI", "ZBH", "DLTR", "EW", "BXP", "APA", "NLSN", "PCAR", "HIG", "TROW", "WEC", "ES", "MTB", "ROP", "CTL", "ABC", "FIS", "ADI", "DPS", "APH", "CMI", "PAYX", "TAP", "GGP", "WLTW", "IP", "CERN", "NVDA", "MCO", "VNO", "CLX", "AMP", "STJ", "CMG", "ATVI", "DTE", "SNDK", "SJM", "IR", "XRAY", "HCP", "TYC", "FE", "SWK", "LVLT", "UA", "O", "PH", "ESS", "BEN", "GPC", "NUE", "BCR", "NTRS", "NBL", "HSIC", "ROK", "MJN", "NEM", "M", "FITB", "SWKS", "VMC", "VIAB", "FAST", "ETR", "HES", "EXPE", "HSY", "MAR", "CXO", "A", "RHT", "ADS", "CAM", "EFX", "WHR", "IVZ", "ADSK", "DVN", "GWW", "NOV", "RCL", "SYMC", "MU", "AA", "HST", "AWK", "TSCO", "FOX", "XLNX", "HOT", "LRCX", "FCX", "DVA", "COL", "HRL", "CHD", "VRSK", "CTXS", "AEE", "MHK", "LH", "CFG", "AAP", "HBI", "MSI", "WDC", "AME", "KIM", "RSG", "WFM", "CPB", "CMS", "COH", "NWL", "MAT", "PFG", "WMB", "STX", "MKC", "KORS", "KLAC", "RF", "TSO", "MAC", "XL", "EXR", "WAT", "FRT", "L", "CCE", "LLTC", "KMX", "EMN", "UHS", "MLM", "CHRW", "XRX", "BBY", "DGX", "COG", "HRS", "MAS", "AKAM", "LNC", "MCHP", "DOV", "SRCL", "WU", "DHI", "MOS", "WRK", "UDR", "CINF", "SCG", "BLL", "HOG", "SLG", "KEY", "LLL", "TXT", "KSS", "SEE", "KSU", "JNPR", "MRO", "ARG", "EQT", "PNR", "EXPD", "CA", "GT", "SIG", "CPGX", "WYN", "HAS", "ENDP", "IFF", "XEC", "SNA", "IPG", "VRSN", "CNP", "BBBY", "AMG", "LEN", "CF", "BWA", "TIF", "CBG", "NTAP", "MNK", "HBAN", "CTAS", "GAS", "UNM", "VAR", "JWN", "PNW", "DRI", "NDAQ", "TSS", "JBHT", "AES", "ETFC", "FLR", "CVC", "NI", "FFIV", "PVH", "TRIP", "DISCK", "XYL", "GPS", "WYNN", "ADT", "HP", "CMA", "HRB", "TMK", "TE", "AVY", "QRVO", "FTI", "LEG", "SPLS", "FTR", "AIV", "IRM", "SNI", "ALLE", "FLS", "PHM", "OKE", "RL", "HAR", "RHI", "URI", "POM", "TGNA", "PKI", "FMC", "FSLR", "RRC", "AIZ", "JEC", "LUK", "NFX", "ZION", "PBCT", "GRMN", "FLIR", "NWSA", "NAVI", "NRG", "DISCA", "PBI", "AN", "MUR", "RIG", "PWR", "PDCO", "LM", "TDC", "DNB", "CSRA", "GME", "R", "SWN", "URBN", "THC", "ESV", "CHK", "OI", "DO", "NWS", "GMCR"];

