module.exports = {
 SPX: [{"Symbol":"AAPL","Sector":"Information Technology","Name":"Apple Inc."},
{"Symbol":"MSFT","Sector":"Information Technology","Name":"Microsoft Corporation"},
{"Symbol":"XOM","Sector":"Energy","Name":"Exxon Mobil Corporation"},
{"Symbol":"JNJ","Sector":"Health Care","Name":"Johnson & Johnson"},
{"Symbol":"GE","Sector":"Industrials","Name":"General Electric Company"},
{"Symbol":"FB","Sector":"Information Technology","Name":"Facebook Inc. Class A"},
{"Symbol":"T","Sector":"Telecommunication Services","Name":"AT&T Inc."},
{"Symbol":"WFC","Sector":"Financials","Name":"Wells Fargo & Company"},
{"Symbol":"PG","Sector":"Consumer Staples","Name":"Procter & Gamble Company"},
{"Symbol":"AMZN","Sector":"Consumer Discretionary","Name":"Amazon.com Inc."},
{"Symbol":"JPM","Sector":"Financials","Name":"JPMorgan Chase & Co."},
{"Symbol":"GOOGL","Sector":"Information Technology","Name":"Alphabet Inc. Class A"},
{"Symbol":"GOOG","Sector":"Information Technology","Name":"Alphabet Inc. Class C"},
{"Symbol":"VZ","Sector":"Telecommunication Services","Name":"Verizon Communications Inc."},
{"Symbol":"PFE","Sector":"Health Care","Name":"Pfizer Inc."},
{"Symbol":"CVX","Sector":"Energy","Name":"Chevron Corporation"},
{"Symbol":"KO","Sector":"Consumer Staples","Name":"Coca-Cola Company"},
{"Symbol":"HD","Sector":"Consumer Discretionary","Name":"Home Depot Inc."},
{"Symbol":"INTC","Sector":"Information Technology","Name":"Intel Corporation"},
{"Symbol":"PM","Sector":"Consumer Staples","Name":"Philip Morris International Inc."},
{"Symbol":"DIS","Sector":"Consumer Discretionary","Name":"Walt Disney Company"},
{"Symbol":"MRK","Sector":"Health Care","Name":"Merck & Co. Inc."},
{"Symbol":"PEP","Sector":"Consumer Staples","Name":"PepsiCo Inc."},
{"Symbol":"CMCSA","Sector":"Consumer Discretionary","Name":"Comcast Corporation Class A"},
{"Symbol":"BAC","Sector":"Financials","Name":"Bank of America Corporation"},
{"Symbol":"CSCO","Sector":"Information Technology","Name":"Cisco Systems Inc."},
{"Symbol":"V","Sector":"Information Technology","Name":"Visa Inc. Class A"},
{"Symbol":"C","Sector":"Financials","Name":"Citigroup Inc."},
{"Symbol":"IBM","Sector":"Information Technology","Name":"International Business Machines Corporation"},
{"Symbol":"ORCL","Sector":"Information Technology","Name":"Oracle Corporation"},
{"Symbol":"GILD","Sector":"Health Care","Name":"Gilead Sciences Inc."},
{"Symbol":"MO","Sector":"Consumer Staples","Name":"Altria Group Inc."},
{"Symbol":"UNH","Sector":"Health Care","Name":"UnitedHealth Group Incorporated"},
{"Symbol":"AGN","Sector":"Health Care","Name":"Allergan plc"},
{"Symbol":"MCD","Sector":"Consumer Discretionary","Name":"McDonald's Corporation"},
{"Symbol":"CVS","Sector":"Consumer Staples","Name":"CVS Health Corporation"},
{"Symbol":"AMGN","Sector":"Health Care","Name":"Amgen Inc."},
{"Symbol":"MDT","Sector":"Health Care","Name":"Medtronic Plc"},
{"Symbol":"BMY","Sector":"Health Care","Name":"Bristol-Myers Squibb Company"},
{"Symbol":"WMT","Sector":"Consumer Staples","Name":"Wal-Mart Stores Inc."},
{"Symbol":"MMM","Sector":"Industrials","Name":"3M Company"},
{"Symbol":"SLB","Sector":"Energy","Name":"Schlumberger NV"},
{"Symbol":"ABBV","Sector":"Health Care","Name":"AbbVie Inc."},
{"Symbol":"MA","Sector":"Information Technology","Name":"MasterCard Incorporated Class A"},
{"Symbol":"SBUX","Sector":"Consumer Discretionary","Name":"Starbucks Corporation"},
{"Symbol":"HON","Sector":"Industrials","Name":"Honeywell International Inc."},
{"Symbol":"NKE","Sector":"Consumer Discretionary","Name":"NIKE Inc. Class B"},
{"Symbol":"CELG","Sector":"Health Care","Name":"Celgene Corporation"},
{"Symbol":"BA","Sector":"Industrials","Name":"Boeing Company"},
{"Symbol":"QCOM","Sector":"Information Technology","Name":"QUALCOMM Incorporated"},
{"Symbol":"UTX","Sector":"Industrials","Name":"United Technologies Corporation"},
{"Symbol":"LLY","Sector":"Health Care","Name":"Eli Lilly and Company"},
{"Symbol":"WBA","Sector":"Consumer Staples","Name":"Walgreens Boots Alliance Inc"},
{"Symbol":"UPS","Sector":"Industrials","Name":"United Parcel Service Inc. Class B"},
{"Symbol":"UNP","Sector":"Industrials","Name":"Union Pacific Corporation"},
{"Symbol":"MDLZ","Sector":"Consumer Staples","Name":"Mondelez International Inc. Class A"},
{"Symbol":"COST","Sector":"Consumer Staples","Name":"Costco Wholesale Corporation"},
{"Symbol":"USB","Sector":"Financials","Name":"U.S. Bancorp"},
{"Symbol":"ACN","Sector":"Information Technology","Name":"Accenture Plc"},
{"Symbol":"PCLN","Sector":"Consumer Discretionary","Name":"Priceline Group Inc"},
{"Symbol":"LOW","Sector":"Consumer Discretionary","Name":"Lowe's Companies Inc."},
{"Symbol":"SPG","Sector":"Financials","Name":"Simon Property Group Inc."},
{"Symbol":"CL","Sector":"Consumer Staples","Name":"Colgate-Palmolive Company"},
{"Symbol":"GS","Sector":"Financials","Name":"Goldman Sachs Group Inc."},
{"Symbol":"AIG","Sector":"Financials","Name":"American International Group Inc."},
{"Symbol":"ABT","Sector":"Health Care","Name":"Abbott Laboratories"},
{"Symbol":"BIIB","Sector":"Health Care","Name":"Biogen Inc."},
{"Symbol":"AVGO","Sector":"Information Technology","Name":"Broadcom Limited"},
{"Symbol":"LMT","Sector":"Industrials","Name":"Lockheed Martin Corporation"},
{"Symbol":"DOW","Sector":"Materials","Name":"Dow Chemical Company"},
{"Symbol":"TXN","Sector":"Information Technology","Name":"Texas Instruments Incorporated"},
{"Symbol":"TWX","Sector":"Consumer Discretionary","Name":"Time Warner Inc."},
{"Symbol":"TMO","Sector":"Health Care","Name":"Thermo Fisher Scientific Inc."},
{"Symbol":"DD","Sector":"Materials","Name":"E. I. du Pont de Nemours and Company"},
{"Symbol":"TWC","Sector":"Consumer Discretionary","Name":"Time Warner Cable Inc."},
{"Symbol":"CB","Sector":"Financials","Name":"Chubb Limited"},
{"Symbol":"DHR","Sector":"Industrials","Name":"Danaher Corporation"},
{"Symbol":"DUK","Sector":"Utilities","Name":"Duke Energy Corporation"},
{"Symbol":"OXY","Sector":"Energy","Name":"Occidental Petroleum Corporation"},
{"Symbol":"NEE","Sector":"Utilities","Name":"NextEra Energy Inc."},
{"Symbol":"F","Sector":"Consumer Discretionary","Name":"Ford Motor Company"},
{"Symbol":"EMC","Sector":"Information Technology","Name":"EMC Corporation"},
{"Symbol":"TJX","Sector":"Consumer Discretionary","Name":"TJX Companies Inc."},
{"Symbol":"TGT","Sector":"Consumer Discretionary","Name":"Target Corporation"},
{"Symbol":"COP","Sector":"Energy","Name":"ConocoPhillips"},
{"Symbol":"AXP","Sector":"Financials","Name":"American Express Company"},
{"Symbol":"MET","Sector":"Financials","Name":"MetLife Inc."},
{"Symbol":"KMB","Sector":"Consumer Staples","Name":"Kimberly-Clark Corporation"},
{"Symbol":"ESRX","Sector":"Health Care","Name":"Express Scripts Holding Company"},
{"Symbol":"KHC","Sector":"Consumer Staples","Name":"Kraft Heinz Company"},
{"Symbol":"SO","Sector":"Utilities","Name":"Southern Company"},
{"Symbol":"CRM","Sector":"Information Technology","Name":"salesforce.com inc."},
{"Symbol":"GM","Sector":"Consumer Discretionary","Name":"General Motors Company"},
{"Symbol":"PYPL","Sector":"Information Technology","Name":"PayPal Holdings Inc"},
{"Symbol":"PNC","Sector":"Financials","Name":"PNC Financial Services Group Inc."},
{"Symbol":"D","Sector":"Utilities","Name":"Dominion Resources Inc."},
{"Symbol":"ADBE","Sector":"Information Technology","Name":"Adobe Systems Incorporated"},
{"Symbol":"BLK","Sector":"Financials","Name":"BlackRock Inc."},
{"Symbol":"CAT","Sector":"Industrials","Name":"Caterpillar Inc."},
{"Symbol":"RAI","Sector":"Consumer Staples","Name":"Reynolds American Inc."},
{"Symbol":"NFLX","Sector":"Consumer Discretionary","Name":"Netflix Inc."},
{"Symbol":"AMT","Sector":"Financials","Name":"American Tower Corporation"},
{"Symbol":"EOG","Sector":"Energy","Name":"EOG Resources Inc."},
{"Symbol":"BK","Sector":"Financials","Name":"Bank of New York Mellon Corporation"},
{"Symbol":"PSX","Sector":"Energy","Name":"Phillips 66"},
{"Symbol":"GD","Sector":"Industrials","Name":"General Dynamics Corporation"},
{"Symbol":"ADP","Sector":"Information Technology","Name":"Automatic Data Processing Inc."},
{"Symbol":"MON","Sector":"Materials","Name":"Monsanto Company"},
{"Symbol":"AET","Sector":"Health Care","Name":"Aetna Inc."},
{"Symbol":"MS","Sector":"Financials","Name":"Morgan Stanley"},
{"Symbol":"MCK","Sector":"Health Care","Name":"McKesson Corporation"},
{"Symbol":"PSA","Sector":"Financials","Name":"Public Storage"},
{"Symbol":"COF","Sector":"Financials","Name":"Capital One Financial Corporation"},
{"Symbol":"FDX","Sector":"Industrials","Name":"FedEx Corporation"},
{"Symbol":"DAL","Sector":"Industrials","Name":"Delta Air Lines Inc."},
{"Symbol":"KR","Sector":"Consumer Staples","Name":"Kroger Co."},
{"Symbol":"CI","Sector":"Health Care","Name":"Cigna Corporation"},
{"Symbol":"ANTM","Sector":"Health Care","Name":"Anthem Inc."},
{"Symbol":"RTN","Sector":"Industrials","Name":"Raytheon Company"},
{"Symbol":"GIS","Sector":"Consumer Staples","Name":"General Mills Inc."},
{"Symbol":"CTSH","Sector":"Information Technology","Name":"Cognizant Technology Solutions Corporation Class A"},
{"Symbol":"NOC","Sector":"Industrials","Name":"Northrop Grumman Corporation"},
{"Symbol":"TRV","Sector":"Financials","Name":"Travelers Companies Inc."},
{"Symbol":"KMI","Sector":"Energy","Name":"Kinder Morgan Inc Class P"},
{"Symbol":"SCHW","Sector":"Financials","Name":"Charles Schwab Corporation"},
{"Symbol":"EMR","Sector":"Industrials","Name":"Emerson Electric Co."},
{"Symbol":"SYK","Sector":"Health Care","Name":"Stryker Corporation"},
{"Symbol":"PRU","Sector":"Financials","Name":"Prudential Financial Inc."},
{"Symbol":"FOXA","Sector":"Consumer Discretionary","Name":"Twenty-First Century Fox Inc. Class A"},
{"Symbol":"ITW","Sector":"Industrials","Name":"Illinois Tool Works Inc."},
{"Symbol":"CME","Sector":"Financials","Name":"CME Group Inc. Class A"},
{"Symbol":"YUM","Sector":"Consumer Discretionary","Name":"Yum! Brands Inc."},
{"Symbol":"EXC","Sector":"Utilities","Name":"Exelon Corporation"},
{"Symbol":"PX","Sector":"Materials","Name":"Praxair Inc."},
{"Symbol":"BDX","Sector":"Health Care","Name":"Becton Dickinson and Company"},
{"Symbol":"AEP","Sector":"Utilities","Name":"American Electric Power Company Inc."},
{"Symbol":"VLO","Sector":"Energy","Name":"Valero Energy Corporation"},
{"Symbol":"LYB","Sector":"Materials","Name":"LyondellBasell Industries NV"},
{"Symbol":"ALXN","Sector":"Health Care","Name":"Alexion Pharmaceuticals Inc."},
{"Symbol":"HAL","Sector":"Energy","Name":"Halliburton Company"},
{"Symbol":"MMC","Sector":"Financials","Name":"Marsh & McLennan Companies Inc."},
{"Symbol":"YHOO","Sector":"Information Technology","Name":"Yahoo! Inc."},
{"Symbol":"HPE","Sector":"Information Technology","Name":"Hewlett Packard Enterprise Co."},
{"Symbol":"REGN","Sector":"Health Care","Name":"Regeneron Pharmaceuticals Inc."},
{"Symbol":"CCI","Sector":"Financials","Name":"Crown Castle International Corp"},
{"Symbol":"PPG","Sector":"Materials","Name":"PPG Industries Inc."},
{"Symbol":"ECL","Sector":"Materials","Name":"Ecolab Inc."},
{"Symbol":"PCG","Sector":"Utilities","Name":"PG&E Corporation"},
{"Symbol":"LUV","Sector":"Industrials","Name":"Southwest Airlines Co."},
{"Symbol":"ICE","Sector":"Financials","Name":"Intercontinental Exchange Inc."},
{"Symbol":"ETN","Sector":"Industrials","Name":"Eaton Corp. Plc"},
{"Symbol":"HUM","Sector":"Health Care","Name":"Humana Inc."},
{"Symbol":"CAH","Sector":"Health Care","Name":"Cardinal Health Inc."},
{"Symbol":"AON","Sector":"Financials","Name":"Aon plc"},
{"Symbol":"ORLY","Sector":"Consumer Discretionary","Name":"O'Reilly Automotive Inc."},
{"Symbol":"BBT","Sector":"Financials","Name":"BB&T Corporation"},
{"Symbol":"AFL","Sector":"Financials","Name":"Aflac Incorporated"},
{"Symbol":"AAL","Sector":"Industrials","Name":"American Airlines Group Inc."},
{"Symbol":"EQR","Sector":"Financials","Name":"Equity Residential"},
{"Symbol":"EBAY","Sector":"Information Technology","Name":"eBay Inc."},
{"Symbol":"APD","Sector":"Materials","Name":"Air Products and Chemicals Inc."},
{"Symbol":"INTU","Sector":"Information Technology","Name":"Intuit Inc."},
{"Symbol":"DE","Sector":"Industrials","Name":"Deere & Company"},
{"Symbol":"MHFI","Sector":"Financials","Name":"McGraw Hill Financial Inc."},
{"Symbol":"CSX","Sector":"Industrials","Name":"CSX Corporation"},
{"Symbol":"ALL","Sector":"Financials","Name":"Allstate Corporation"},
{"Symbol":"AVB","Sector":"Financials","Name":"AvalonBay Communities Inc."},
{"Symbol":"DG","Sector":"Consumer Discretionary","Name":"Dollar General Corporation"},
{"Symbol":"STZ","Sector":"Consumer Staples","Name":"Constellation Brands Inc. Class A"},
{"Symbol":"PPL","Sector":"Utilities","Name":"PPL Corporation"},
{"Symbol":"AZO","Sector":"Consumer Discretionary","Name":"AutoZone Inc."},
{"Symbol":"BSX","Sector":"Health Care","Name":"Boston Scientific Corporation"},
{"Symbol":"JCI","Sector":"Consumer Discretionary","Name":"Johnson Controls Inc."},
{"Symbol":"WM","Sector":"Industrials","Name":"Waste Management Inc."},
{"Symbol":"SYF","Sector":"Financials","Name":"Synchrony Financial"},
{"Symbol":"SYY","Sector":"Consumer Staples","Name":"Sysco Corporation"},
{"Symbol":"NSC","Sector":"Industrials","Name":"Norfolk Southern Corporation"},
{"Symbol":"HCN","Sector":"Financials","Name":"Welltower Inc."},
{"Symbol":"HCA","Sector":"Health Care","Name":"HCA Holdings Inc."},
{"Symbol":"ROST","Sector":"Consumer Discretionary","Name":"Ross Stores Inc."},
{"Symbol":"STT","Sector":"Financials","Name":"State Street Corporation"},
{"Symbol":"APC","Sector":"Energy","Name":"Anadarko Petroleum Corporation"},
{"Symbol":"SRE","Sector":"Utilities","Name":"Sempra Energy"},
{"Symbol":"ILMN","Sector":"Health Care","Name":"Illumina Inc."},
{"Symbol":"TEL","Sector":"Information Technology","Name":"TE Connectivity Ltd."},
{"Symbol":"CBS","Sector":"Consumer Discretionary","Name":"CBS Corporation Class B"},
{"Symbol":"AMAT","Sector":"Information Technology","Name":"Applied Materials Inc."},
{"Symbol":"BXLT","Sector":"Health Care","Name":"Baxalta Inc."},
{"Symbol":"EIX","Sector":"Utilities","Name":"Edison International"},
{"Symbol":"WY","Sector":"Financials","Name":"Weyerhaeuser Company"},
{"Symbol":"VFC","Sector":"Consumer Discretionary","Name":"V.F. Corporation"},
{"Symbol":"PEG","Sector":"Utilities","Name":"Public Service Enterprise Group Incorporated"},
{"Symbol":"SHW","Sector":"Materials","Name":"Sherwin-Williams Company"},
{"Symbol":"FISV","Sector":"Information Technology","Name":"Fiserv Inc."},
{"Symbol":"PLD","Sector":"Financials","Name":"Prologis Inc."},
{"Symbol":"PXD","Sector":"Energy","Name":"Pioneer Natural Resources Company"},
{"Symbol":"CCL","Sector":"Consumer Discretionary","Name":"Carnival Corporation"},
{"Symbol":"LB","Sector":"Consumer Discretionary","Name":"L Brands Inc."},
{"Symbol":"BAX","Sector":"Health Care","Name":"Baxter International Inc."},
{"Symbol":"ADM","Sector":"Consumer Staples","Name":"Archer-Daniels-Midland Company"},
{"Symbol":"UAL","Sector":"Industrials","Name":"United Continental Holdings Inc."},
{"Symbol":"EQIX","Sector":"Financials","Name":"Equinix Inc."},
{"Symbol":"ISRG","Sector":"Health Care","Name":"Intuitive Surgical Inc."},
{"Symbol":"GLW","Sector":"Information Technology","Name":"Corning Incorporated"},
{"Symbol":"ED","Sector":"Utilities","Name":"Consolidated Edison Inc."},
{"Symbol":"VRTX","Sector":"Health Care","Name":"Vertex Pharmaceuticals Incorporated"},
{"Symbol":"HPQ","Sector":"Information Technology","Name":"HP Inc."},
{"Symbol":"DFS","Sector":"Financials","Name":"Discover Financial Services"},
{"Symbol":"EL","Sector":"Consumer Staples","Name":"Estee Lauder Companies Inc. Class A"},
{"Symbol":"SE","Sector":"Energy","Name":"Spectra Energy Corp"},
{"Symbol":"XEL","Sector":"Utilities","Name":"Xcel Energy Inc."},
{"Symbol":"MPC","Sector":"Energy","Name":"Marathon Petroleum Corporation"},
{"Symbol":"MYL","Sector":"Health Care","Name":"Mylan N.V."},
{"Symbol":"EA","Sector":"Information Technology","Name":"Electronic Arts Inc."},
{"Symbol":"MNST","Sector":"Consumer Staples","Name":"Monster Beverage Corporation"},
{"Symbol":"TSN","Sector":"Consumer Staples","Name":"Tyson Foods Inc. Class A"},
{"Symbol":"PRGO","Sector":"Health Care","Name":"Perrigo Co. Plc"},
{"Symbol":"VTR","Sector":"Financials","Name":"Ventas Inc."},
{"Symbol":"BHI","Sector":"Energy","Name":"Baker Hughes Incorporated"},
{"Symbol":"DLPH","Sector":"Consumer Discretionary","Name":"Delphi Automotive PLC"},
{"Symbol":"PGR","Sector":"Financials","Name":"Progressive Corporation"},
{"Symbol":"K","Sector":"Consumer Staples","Name":"Kellogg Company"},
{"Symbol":"OMC","Sector":"Consumer Discretionary","Name":"Omnicom Group Inc"},
{"Symbol":"ZTS","Sector":"Health Care","Name":"Zoetis Inc. Class A"},
{"Symbol":"CAG","Sector":"Consumer Staples","Name":"ConAgra Foods Inc."},
{"Symbol":"STI","Sector":"Financials","Name":"SunTrust Banks Inc."},
{"Symbol":"ZBH","Sector":"Health Care","Name":"Zimmer Biomet Holdings Inc."},
{"Symbol":"DLTR","Sector":"Consumer Discretionary","Name":"Dollar Tree Inc."},
{"Symbol":"EW","Sector":"Health Care","Name":"Edwards Lifesciences Corporation"},
{"Symbol":"BXP","Sector":"Financials","Name":"Boston Properties Inc."},
{"Symbol":"APA","Sector":"Energy","Name":"Apache Corporation"},
{"Symbol":"NLSN","Sector":"Industrials","Name":"Nielsen Holdings Plc"},
{"Symbol":"PCAR","Sector":"Industrials","Name":"PACCAR Inc"},
{"Symbol":"HIG","Sector":"Financials","Name":"Hartford Financial Services Group Inc."},
{"Symbol":"TROW","Sector":"Financials","Name":"T. Rowe Price Group"},
{"Symbol":"WEC","Sector":"Utilities","Name":"WEC Energy Group Inc"},
{"Symbol":"ES","Sector":"Utilities","Name":"Eversource Energy"},
{"Symbol":"MTB","Sector":"Financials","Name":"M&T Bank Corporation"},
{"Symbol":"ROP","Sector":"Industrials","Name":"Roper Technologies Inc."},
{"Symbol":"CTL","Sector":"Telecommunication Services","Name":"CenturyLink Inc."},
{"Symbol":"ABC","Sector":"Health Care","Name":"AmerisourceBergen Corporation"},
{"Symbol":"FIS","Sector":"Information Technology","Name":"Fidelity National Information Services Inc."},
{"Symbol":"ADI","Sector":"Information Technology","Name":"Analog Devices Inc."},
{"Symbol":"DPS","Sector":"Consumer Staples","Name":"Dr Pepper Snapple Group Inc."},
{"Symbol":"APH","Sector":"Information Technology","Name":"Amphenol Corporation Class A"},
{"Symbol":"CMI","Sector":"Industrials","Name":"Cummins Inc."},
{"Symbol":"PAYX","Sector":"Information Technology","Name":"Paychex Inc."},
{"Symbol":"TAP","Sector":"Consumer Staples","Name":"Molson Coors Brewing Company Class B"},
{"Symbol":"GGP","Sector":"Financials","Name":"General Growth Properties Inc."},
{"Symbol":"WLTW","Sector":"Financials","Name":"Willis Towers Watson Public Limited Company"},
{"Symbol":"IP","Sector":"Materials","Name":"International Paper Company"},
{"Symbol":"CERN","Sector":"Health Care","Name":"Cerner Corporation"},
{"Symbol":"NVDA","Sector":"Information Technology","Name":"NVIDIA Corporation"},
{"Symbol":"MCO","Sector":"Financials","Name":"Moody's Corporation"},
{"Symbol":"VNO","Sector":"Financials","Name":"Vornado Realty Trust"},
{"Symbol":"CLX","Sector":"Consumer Staples","Name":"Clorox Company"},
{"Symbol":"AMP","Sector":"Financials","Name":"Ameriprise Financial Inc."},
{"Symbol":"STJ","Sector":"Health Care","Name":"St. Jude Medical Inc."},
{"Symbol":"CMG","Sector":"Consumer Discretionary","Name":"Chipotle Mexican Grill Inc."},
{"Symbol":"ATVI","Sector":"Information Technology","Name":"Activision Blizzard Inc."},
{"Symbol":"DTE","Sector":"Utilities","Name":"DTE Energy Company"},
{"Symbol":"SNDK","Sector":"Information Technology","Name":"SanDisk Corporation"},
{"Symbol":"SJM","Sector":"Consumer Staples","Name":"J. M. Smucker Company"},
{"Symbol":"IR","Sector":"Industrials","Name":"Ingersoll-Rand Plc"},
{"Symbol":"XRAY","Sector":"Health Care","Name":"DENTSPLY SIRONA Inc."},
{"Symbol":"HCP","Sector":"Financials","Name":"HCP Inc."},
{"Symbol":"TYC","Sector":"Industrials","Name":"Tyco International PLC"},
{"Symbol":"FE","Sector":"Utilities","Name":"FirstEnergy Corp."},
{"Symbol":"SWK","Sector":"Industrials","Name":"Stanley Black & Decker Inc."},
{"Symbol":"LVLT","Sector":"Telecommunication Services","Name":"Level 3 Communications Inc."},
{"Symbol":"UA","Sector":"Consumer Discretionary","Name":"Under Armour Inc. Class A"},
{"Symbol":"O","Sector":"Financials","Name":"Realty Income Corporation"},
{"Symbol":"PH","Sector":"Industrials","Name":"Parker-Hannifin Corporation"},
{"Symbol":"ESS","Sector":"Financials","Name":"Essex Property Trust Inc."},
{"Symbol":"BEN","Sector":"Financials","Name":"Franklin Resources Inc."},
{"Symbol":"GPC","Sector":"Consumer Discretionary","Name":"Genuine Parts Company"},
{"Symbol":"NUE","Sector":"Materials","Name":"Nucor Corporation"},
{"Symbol":"BCR","Sector":"Health Care","Name":"C. R. Bard Inc."},
{"Symbol":"NTRS","Sector":"Financials","Name":"Northern Trust Corporation"},
{"Symbol":"NBL","Sector":"Energy","Name":"Noble Energy Inc."},
{"Symbol":"HSIC","Sector":"Health Care","Name":"Henry Schein Inc."},
{"Symbol":"ROK","Sector":"Industrials","Name":"Rockwell Automation Inc."},
{"Symbol":"MJN","Sector":"Consumer Staples","Name":"Mead Johnson Nutrition Company"},
{"Symbol":"NEM","Sector":"Materials","Name":"Newmont Mining Corporation"},
{"Symbol":"M","Sector":"Consumer Discretionary","Name":"Macy's Inc"},
{"Symbol":"FITB","Sector":"Financials","Name":"Fifth Third Bancorp"},
{"Symbol":"SWKS","Sector":"Information Technology","Name":"Skyworks Solutions Inc."},
{"Symbol":"VMC","Sector":"Materials","Name":"Vulcan Materials Company"},
{"Symbol":"VIAB","Sector":"Consumer Discretionary","Name":"Viacom Inc. Class B"},
{"Symbol":"FAST","Sector":"Industrials","Name":"Fastenal Company"},
{"Symbol":"ETR","Sector":"Utilities","Name":"Entergy Corporation"},
{"Symbol":"HES","Sector":"Energy","Name":"Hess Corporation"},
{"Symbol":"EXPE","Sector":"Consumer Discretionary","Name":"Expedia Inc."},
{"Symbol":"HSY","Sector":"Consumer Staples","Name":"Hershey Company"},
{"Symbol":"MAR","Sector":"Consumer Discretionary","Name":"Marriott International Inc. Class A"},
{"Symbol":"CXO","Sector":"Energy","Name":"Concho Resources Inc."},
{"Symbol":"A","Sector":"Health Care","Name":"Agilent Technologies Inc."},
{"Symbol":"RHT","Sector":"Information Technology","Name":"Red Hat Inc."},
{"Symbol":"ADS","Sector":"Information Technology","Name":"Alliance Data Systems Corporation"},
{"Symbol":"CAM","Sector":"Energy","Name":"Cameron International Corporation"},
{"Symbol":"EFX","Sector":"Industrials","Name":"Equifax Inc."},
{"Symbol":"WHR","Sector":"Consumer Discretionary","Name":"Whirlpool Corporation"},
{"Symbol":"IVZ","Sector":"Financials","Name":"Invesco Ltd."},
{"Symbol":"ADSK","Sector":"Information Technology","Name":"Autodesk Inc."},
{"Symbol":"DVN","Sector":"Energy","Name":"Devon Energy Corporation"},
{"Symbol":"GWW","Sector":"Industrials","Name":"W.W. Grainger Inc."},
{"Symbol":"NOV","Sector":"Energy","Name":"National Oilwell Varco Inc."},
{"Symbol":"RCL","Sector":"Consumer Discretionary","Name":"Royal Caribbean Cruises Ltd."},
{"Symbol":"SYMC","Sector":"Information Technology","Name":"Symantec Corporation"},
{"Symbol":"MU","Sector":"Information Technology","Name":"Micron Technology Inc."},
{"Symbol":"AA","Sector":"Materials","Name":"Alcoa Inc."},
{"Symbol":"HST","Sector":"Financials","Name":"Host Hotels & Resorts Inc."},
{"Symbol":"AWK","Sector":"Utilities","Name":"American Water Works Company Inc."},
{"Symbol":"TSCO","Sector":"Consumer Discretionary","Name":"Tractor Supply Company"},
{"Symbol":"FOX","Sector":"Consumer Discretionary","Name":"Twenty-First Century Fox Inc. Class B"},
{"Symbol":"XLNX","Sector":"Information Technology","Name":"Xilinx Inc."},
{"Symbol":"HOT","Sector":"Consumer Discretionary","Name":"Starwood Hotels & Resorts Worldwide Inc."},
{"Symbol":"LRCX","Sector":"Information Technology","Name":"Lam Research Corporation"},
{"Symbol":"FCX","Sector":"Materials","Name":"Freeport-McMoRan Inc."},
{"Symbol":"DVA","Sector":"Health Care","Name":"DaVita HealthCare Partners Inc."},
{"Symbol":"COL","Sector":"Industrials","Name":"Rockwell Collins Inc."},
{"Symbol":"HRL","Sector":"Consumer Staples","Name":"Hormel Foods Corporation"},
{"Symbol":"CHD","Sector":"Consumer Staples","Name":"Church & Dwight Co. Inc."},
{"Symbol":"VRSK","Sector":"Industrials","Name":"Verisk Analytics Inc"},
{"Symbol":"CTXS","Sector":"Information Technology","Name":"Citrix Systems Inc."},
{"Symbol":"AEE","Sector":"Utilities","Name":"Ameren Corporation"},
{"Symbol":"MHK","Sector":"Consumer Discretionary","Name":"Mohawk Industries Inc."},
{"Symbol":"LH","Sector":"Health Care","Name":"Laboratory Corporation of America Holdings"},
{"Symbol":"CFG","Sector":"Financials","Name":"Citizens Financial Group Inc."},
{"Symbol":"AAP","Sector":"Consumer Discretionary","Name":"Advance Auto Parts Inc."},
{"Symbol":"HBI","Sector":"Consumer Discretionary","Name":"Hanesbrands Inc."},
{"Symbol":"MSI","Sector":"Information Technology","Name":"Motorola Solutions Inc."},
{"Symbol":"WDC","Sector":"Information Technology","Name":"Western Digital Corporation"},
{"Symbol":"AME","Sector":"Industrials","Name":"AMETEK Inc."},
{"Symbol":"KIM","Sector":"Financials","Name":"Kimco Realty Corporation"},
{"Symbol":"RSG","Sector":"Industrials","Name":"Republic Services Inc."},
{"Symbol":"WFM","Sector":"Consumer Staples","Name":"Whole Foods Market Inc."},
{"Symbol":"CPB","Sector":"Consumer Staples","Name":"Campbell Soup Company"},
{"Symbol":"CMS","Sector":"Utilities","Name":"CMS Energy Corporation"},
{"Symbol":"COH","Sector":"Consumer Discretionary","Name":"Coach Inc."},
{"Symbol":"NWL","Sector":"Consumer Discretionary","Name":"Newell Rubbermaid Inc."},
{"Symbol":"MAT","Sector":"Consumer Discretionary","Name":"Mattel Inc."},
{"Symbol":"PFG","Sector":"Financials","Name":"Principal Financial Group Inc."},
{"Symbol":"WMB","Sector":"Energy","Name":"Williams Companies Inc."},
{"Symbol":"STX","Sector":"Information Technology","Name":"Seagate Technology PLC"},
{"Symbol":"MKC","Sector":"Consumer Staples","Name":"McCormick & Company Incorporated"},
{"Symbol":"KORS","Sector":"Consumer Discretionary","Name":"Michael Kors Holdings Ltd"},
{"Symbol":"KLAC","Sector":"Information Technology","Name":"KLA-Tencor Corporation"},
{"Symbol":"RF","Sector":"Financials","Name":"Regions Financial Corporation"},
{"Symbol":"TSO","Sector":"Energy","Name":"Tesoro Corporation"},
{"Symbol":"MAC","Sector":"Financials","Name":"Macerich Company"},
{"Symbol":"XL","Sector":"Financials","Name":"XL Group Plc"},
{"Symbol":"EXR","Sector":"Financials","Name":"Extra Space Storage Inc."},
{"Symbol":"WAT","Sector":"Health Care","Name":"Waters Corporation"},
{"Symbol":"FRT","Sector":"Financials","Name":"Federal Realty Investment Trust"},
{"Symbol":"L","Sector":"Financials","Name":"Loews Corporation"},
{"Symbol":"CCE","Sector":"Consumer Staples","Name":"Coca-Cola Enterprises Inc."},
{"Symbol":"LLTC","Sector":"Information Technology","Name":"Linear Technology Corporation"},
{"Symbol":"KMX","Sector":"Consumer Discretionary","Name":"CarMax Inc."},
{"Symbol":"EMN","Sector":"Materials","Name":"Eastman Chemical Company"},
{"Symbol":"UHS","Sector":"Health Care","Name":"Universal Health Services Inc. Class B"},
{"Symbol":"MLM","Sector":"Materials","Name":"Martin Marietta Materials Inc."},
{"Symbol":"CHRW","Sector":"Industrials","Name":"C.H. Robinson Worldwide Inc."},
{"Symbol":"XRX","Sector":"Information Technology","Name":"Xerox Corporation"},
{"Symbol":"BBY","Sector":"Consumer Discretionary","Name":"Best Buy Co. Inc."},
{"Symbol":"DGX","Sector":"Health Care","Name":"Quest Diagnostics Incorporated"},
{"Symbol":"COG","Sector":"Energy","Name":"Cabot Oil & Gas Corporation"},
{"Symbol":"HRS","Sector":"Information Technology","Name":"Harris Corporation"},
{"Symbol":"MAS","Sector":"Industrials","Name":"Masco Corporation"},
{"Symbol":"AKAM","Sector":"Information Technology","Name":"Akamai Technologies Inc."},
{"Symbol":"LNC","Sector":"Financials","Name":"Lincoln National Corporation"},
{"Symbol":"MCHP","Sector":"Information Technology","Name":"Microchip Technology Incorporated"},
{"Symbol":"DOV","Sector":"Industrials","Name":"Dover Corporation"},
{"Symbol":"SRCL","Sector":"Industrials","Name":"Stericycle Inc."},
{"Symbol":"WU","Sector":"Information Technology","Name":"Western Union Company"},
{"Symbol":"DHI","Sector":"Consumer Discretionary","Name":"D.R. Horton Inc."},
{"Symbol":"MOS","Sector":"Materials","Name":"Mosaic Company"},
{"Symbol":"WRK","Sector":"Materials","Name":"WestRock Co."},
{"Symbol":"UDR","Sector":"Financials","Name":"UDR Inc."},
{"Symbol":"CINF","Sector":"Financials","Name":"Cincinnati Financial Corporation"},
{"Symbol":"SCG","Sector":"Utilities","Name":"SCANA Corporation"},
{"Symbol":"BLL","Sector":"Materials","Name":"Ball Corporation"},
{"Symbol":"HOG","Sector":"Consumer Discretionary","Name":"Harley-Davidson Inc."},
{"Symbol":"SLG","Sector":"Financials","Name":"SL Green Realty Corp."},
{"Symbol":"KEY","Sector":"Financials","Name":"KeyCorp"},
{"Symbol":"LLL","Sector":"Industrials","Name":"L-3 Communications Holdings Inc."},
{"Symbol":"TXT","Sector":"Industrials","Name":"Textron Inc."},
{"Symbol":"KSS","Sector":"Consumer Discretionary","Name":"Kohl's Corporation"},
{"Symbol":"SEE","Sector":"Materials","Name":"Sealed Air Corporation"},
{"Symbol":"KSU","Sector":"Industrials","Name":"Kansas City Southern"},
{"Symbol":"JNPR","Sector":"Information Technology","Name":"Juniper Networks Inc."},
{"Symbol":"MRO","Sector":"Energy","Name":"Marathon Oil Corporation"},
{"Symbol":"ARG","Sector":"Materials","Name":"Airgas Inc."},
{"Symbol":"EQT","Sector":"Energy","Name":"EQT Corporation"},
{"Symbol":"PNR","Sector":"Industrials","Name":"Pentair plc"},
{"Symbol":"EXPD","Sector":"Industrials","Name":"Expeditors International of Washington Inc."},
{"Symbol":"CA","Sector":"Information Technology","Name":"CA Inc."},
{"Symbol":"GT","Sector":"Consumer Discretionary","Name":"Goodyear Tire & Rubber Company"},
{"Symbol":"SIG","Sector":"Consumer Discretionary","Name":"Signet Jewelers Limited"},
{"Symbol":"CPGX","Sector":"Energy","Name":"Columbia Pipeline Group Inc"},
{"Symbol":"WYN","Sector":"Consumer Discretionary","Name":"Wyndham Worldwide Corporation"},
{"Symbol":"HAS","Sector":"Consumer Discretionary","Name":"Hasbro Inc."},
{"Symbol":"ENDP","Sector":"Health Care","Name":"Endo International Plc"},
{"Symbol":"IFF","Sector":"Materials","Name":"International Flavors & Fragrances Inc."},
{"Symbol":"XEC","Sector":"Energy","Name":"Cimarex Energy Co."},
{"Symbol":"SNA","Sector":"Industrials","Name":"Snap-on Incorporated"},
{"Symbol":"IPG","Sector":"Consumer Discretionary","Name":"Interpublic Group of Companies Inc."},
{"Symbol":"VRSN","Sector":"Information Technology","Name":"VeriSign Inc."},
{"Symbol":"CNP","Sector":"Utilities","Name":"CenterPoint Energy Inc."},
{"Symbol":"BBBY","Sector":"Consumer Discretionary","Name":"Bed Bath & Beyond Inc."},
{"Symbol":"AMG","Sector":"Financials","Name":"Affiliated Managers Group Inc."},
{"Symbol":"LEN","Sector":"Consumer Discretionary","Name":"Lennar Corporation Class A"},
{"Symbol":"CF","Sector":"Materials","Name":"CF Industries Holdings Inc."},
{"Symbol":"BWA","Sector":"Consumer Discretionary","Name":"BorgWarner Inc."},
{"Symbol":"TIF","Sector":"Consumer Discretionary","Name":"Tiffany & Co."},
{"Symbol":"CBG","Sector":"Financials","Name":"CBRE Group Inc. Class A"},
{"Symbol":"NTAP","Sector":"Information Technology","Name":"NetApp Inc."},
{"Symbol":"MNK","Sector":"Health Care","Name":"Mallinckrodt Plc"},
{"Symbol":"HBAN","Sector":"Financials","Name":"Huntington Bancshares Incorporated"},
{"Symbol":"CTAS","Sector":"Industrials","Name":"Cintas Corporation"},
{"Symbol":"GAS","Sector":"Utilities","Name":"AGL Resources Inc."},
{"Symbol":"UNM","Sector":"Financials","Name":"Unum Group"},
{"Symbol":"VAR","Sector":"Health Care","Name":"Varian Medical Systems Inc."},
{"Symbol":"JWN","Sector":"Consumer Discretionary","Name":"Nordstrom Inc."},
{"Symbol":"PNW","Sector":"Utilities","Name":"Pinnacle West Capital Corporation"},
{"Symbol":"DRI","Sector":"Consumer Discretionary","Name":"Darden Restaurants Inc."},
{"Symbol":"NDAQ","Sector":"Financials","Name":"Nasdaq Inc."},
{"Symbol":"TSS","Sector":"Information Technology","Name":"Total System Services Inc."},
{"Symbol":"JBHT","Sector":"Industrials","Name":"J.B. Hunt Transport Services Inc."},
{"Symbol":"AES","Sector":"Utilities","Name":"AES Corporation"},
{"Symbol":"ETFC","Sector":"Financials","Name":"E*TRADE Financial Corporation"},
{"Symbol":"FLR","Sector":"Industrials","Name":"Fluor Corporation"},
{"Symbol":"CVC","Sector":"Consumer Discretionary","Name":"Cablevision Systems Corporation Class A"},
{"Symbol":"NI","Sector":"Utilities","Name":"NiSource Inc."},
{"Symbol":"FFIV","Sector":"Information Technology","Name":"F5 Networks Inc."},
{"Symbol":"PVH","Sector":"Consumer Discretionary","Name":"PVH Corp."},
{"Symbol":"TRIP","Sector":"Consumer Discretionary","Name":"TripAdvisor Inc."},
{"Symbol":"DISCK","Sector":"Consumer Discretionary","Name":"Discovery Communications Inc. Class C"},
{"Symbol":"XYL","Sector":"Industrials","Name":"Xylem Inc."},
{"Symbol":"GPS","Sector":"Consumer Discretionary","Name":"Gap Inc."},
{"Symbol":"WYNN","Sector":"Consumer Discretionary","Name":"Wynn Resorts Limited"},
{"Symbol":"ADT","Sector":"Industrials","Name":"ADT Corporation"},
{"Symbol":"HP","Sector":"Energy","Name":"Helmerich & Payne Inc."},
{"Symbol":"CMA","Sector":"Financials","Name":"Comerica Incorporated"},
{"Symbol":"HRB","Sector":"Consumer Discretionary","Name":"H&R Block Inc."},
{"Symbol":"TMK","Sector":"Financials","Name":"Torchmark Corporation"},
{"Symbol":"TE","Sector":"Utilities","Name":"TECO Energy Inc."},
{"Symbol":"AVY","Sector":"Materials","Name":"Avery Dennison Corporation"},
{"Symbol":"QRVO","Sector":"Information Technology","Name":"Qorvo Inc."},
{"Symbol":"FTI","Sector":"Energy","Name":"FMC Technologies Inc."},
{"Symbol":"LEG","Sector":"Consumer Discretionary","Name":"Leggett & Platt Incorporated"},
{"Symbol":"SPLS","Sector":"Consumer Discretionary","Name":"Staples Inc."},
{"Symbol":"FTR","Sector":"Telecommunication Services","Name":"Frontier Communications Corporation"},
{"Symbol":"AIV","Sector":"Financials","Name":"Apartment Investment and Management Company Class A"},
{"Symbol":"IRM","Sector":"Financials","Name":"Iron Mountain Inc."},
{"Symbol":"SNI","Sector":"Consumer Discretionary","Name":"Scripps Networks Interactive Inc. Class A"},
{"Symbol":"ALLE","Sector":"Industrials","Name":"Allegion PLC"},
{"Symbol":"FLS","Sector":"Industrials","Name":"Flowserve Corporation"},
{"Symbol":"PHM","Sector":"Consumer Discretionary","Name":"PulteGroup Inc."},
{"Symbol":"OKE","Sector":"Energy","Name":"ONEOK Inc."},
{"Symbol":"RL","Sector":"Consumer Discretionary","Name":"Ralph Lauren Corporation Class A"},
{"Symbol":"HAR","Sector":"Consumer Discretionary","Name":"Harman International Industries Incorporated"},
{"Symbol":"RHI","Sector":"Industrials","Name":"Robert Half International Inc."},
{"Symbol":"URI","Sector":"Industrials","Name":"United Rentals Inc."},
{"Symbol":"POM","Sector":"Utilities","Name":"Pepco Holdings Inc."},
{"Symbol":"TGNA","Sector":"Consumer Discretionary","Name":"TEGNA Inc."},
{"Symbol":"PKI","Sector":"Health Care","Name":"PerkinElmer Inc."},
{"Symbol":"FMC","Sector":"Materials","Name":"FMC Corporation"},
{"Symbol":"FSLR","Sector":"Information Technology","Name":"First Solar Inc."},
{"Symbol":"RRC","Sector":"Energy","Name":"Range Resources Corporation"},
{"Symbol":"AIZ","Sector":"Financials","Name":"Assurant Inc."},
{"Symbol":"JEC","Sector":"Industrials","Name":"Jacobs Engineering Group Inc."},
{"Symbol":"LUK","Sector":"Financials","Name":"Leucadia National Corporation"},
{"Symbol":"NFX","Sector":"Energy","Name":"Newfield Exploration Company"},
{"Symbol":"ZION","Sector":"Financials","Name":"Zions Bancorporation"},
{"Symbol":"PBCT","Sector":"Financials","Name":"People's United Financial Inc."},
{"Symbol":"GRMN","Sector":"Consumer Discretionary","Name":"Garmin Ltd."},
{"Symbol":"FLIR","Sector":"Information Technology","Name":"FLIR Systems Inc."},
{"Symbol":"NWSA","Sector":"Consumer Discretionary","Name":"News Corporation Class A"},
{"Symbol":"NAVI","Sector":"Financials","Name":"Navient Corp"},
{"Symbol":"NRG","Sector":"Utilities","Name":"NRG Energy Inc."},
{"Symbol":"DISCA","Sector":"Consumer Discretionary","Name":"Discovery Communications Inc. Class A"},
{"Symbol":"PBI","Sector":"Industrials","Name":"Pitney Bowes Inc."},
{"Symbol":"AN","Sector":"Consumer Discretionary","Name":"AutoNation Inc."},
{"Symbol":"MUR","Sector":"Energy","Name":"Murphy Oil Corporation"},
{"Symbol":"RIG","Sector":"Energy","Name":"Transocean Ltd."},
{"Symbol":"PWR","Sector":"Industrials","Name":"Quanta Services Inc."},
{"Symbol":"PDCO","Sector":"Health Care","Name":"Patterson Companies Inc."},
{"Symbol":"LM","Sector":"Financials","Name":"Legg Mason Inc."},
{"Symbol":"TDC","Sector":"Information Technology","Name":"Teradata Corporation"},
{"Symbol":"DNB","Sector":"Industrials","Name":"Dun & Bradstreet Corporation"},
{"Symbol":"CSRA","Sector":"Information Technology","Name":"CSRA Inc."},
{"Symbol":"GME","Sector":"Consumer Discretionary","Name":"GameStop Corp. Class A"},
{"Symbol":"R","Sector":"Industrials","Name":"Ryder System Inc."},
{"Symbol":"SWN","Sector":"Energy","Name":"Southwestern Energy Company"},
{"Symbol":"URBN","Sector":"Consumer Discretionary","Name":"Urban Outfitters Inc."},
{"Symbol":"THC","Sector":"Health Care","Name":"Tenet Healthcare Corporation"},
{"Symbol":"ESV","Sector":"Energy","Name":"Ensco plc"},
{"Symbol":"CHK","Sector":"Energy","Name":"Chesapeake Energy Corporation"},
{"Symbol":"OI","Sector":"Materials","Name":"Owens-Illinois Inc."},
{"Symbol":"DO","Sector":"Energy","Name":"Diamond Offshore Drilling Inc."},
{"Symbol":"NWS","Sector":"Consumer Discretionary","Name":"News Corporation Class B"},
{"Symbol":"GMCR","Sector":"Consumer Staples","Name":"Keurig Green Mountain Inc."}]
};


// ["AAPL", "MSFT", "XOM", "JNJ", "GE", "FB", "T", "WFC", "PG", "AMZN", "JPM", "GOOGL", "GOOG", "VZ", "PFE", "CVX", "KO", "HD", "INTC", "PM", "DIS", "MRK", "PEP", "CMCSA", "BAC", "CSCO", "V", "C", "IBM", "ORCL", "GILD", "MO", "UNH", "AGN", "MCD", "CVS", "AMGN", "MDT", "BMY", "WMT", "MMM", "SLB", "ABBV", "MA", "SBUX", "HON", "NKE", "CELG", "BA", "QCOM", "UTX", "LLY", "WBA", "UPS", "UNP", "MDLZ", "COST", "USB", "ACN", "PCLN", "LOW", "SPG", "CL", "GS", "AIG", "ABT", "BIIB", "AVGO", "LMT", "DOW", "TXN", "TWX", "TMO", "DD", "TWC", "CB", "DHR", "DUK", "OXY", "NEE", "F", "EMC", "TJX", "TGT", "COP", "AXP", "MET", "KMB", "ESRX", "KHC", "SO", "CRM", "GM", "PYPL", "PNC", "D", "ADBE", "BLK", "CAT", "RAI", "NFLX", "AMT", "EOG", "BK", "PSX", "GD", "ADP", "MON", "AET", "MS", "MCK", "PSA", "COF", "FDX", "DAL", "KR", "CI", "ANTM", "RTN", "GIS", "CTSH", "NOC", "TRV", "KMI", "SCHW", "EMR", "SYK", "PRU", "FOXA", "ITW", "CME", "YUM", "EXC", "PX", "BDX", "AEP", "VLO", "LYB", "ALXN", "HAL", "MMC", "YHOO", "HPE", "REGN", "CCI", "PPG", "ECL", "PCG", "LUV", "ICE", "ETN", "HUM", "CAH", "AON", "ORLY", "BBT", "AFL", "AAL", "EQR", "EBAY", "APD", "INTU", "DE", "MHFI", "CSX", "ALL", "AVB", "DG", "STZ", "PPL", "AZO", "BSX", "JCI", "WM", "SYF", "SYY", "NSC", "HCN", "HCA", "ROST", "STT", "APC", "SRE", "ILMN", "TEL", "CBS", "AMAT", "BXLT", "EIX", "WY", "VFC", "PEG", "SHW", "FISV", "PLD", "PXD", "CCL", "LB", "BAX", "ADM", "UAL", "EQIX", "ISRG", "GLW", "ED", "VRTX", "HPQ", "DFS", "EL", "SE", "XEL", "MPC", "MYL", "EA", "MNST", "TSN", "PRGO", "VTR", "BHI", "DLPH", "PGR", "K", "OMC", "ZTS", "CAG", "STI", "ZBH", "DLTR", "EW", "BXP", "APA", "NLSN", "PCAR", "HIG", "TROW", "WEC", "ES", "MTB", "ROP", "CTL", "ABC", "FIS", "ADI", "DPS", "APH", "CMI", "PAYX", "TAP", "GGP", "WLTW", "IP", "CERN", "NVDA", "MCO", "VNO", "CLX", "AMP", "STJ", "CMG", "ATVI", "DTE", "SNDK", "SJM", "IR", "XRAY", "HCP", "TYC", "FE", "SWK", "LVLT", "UA", "O", "PH", "ESS", "BEN", "GPC", "NUE", "BCR", "NTRS", "NBL", "HSIC", "ROK", "MJN", "NEM", "M", "FITB", "SWKS", "VMC", "VIAB", "FAST", "ETR", "HES", "EXPE", "HSY", "MAR", "CXO", "A", "RHT", "ADS", "CAM", "EFX", "WHR", "IVZ", "ADSK", "DVN", "GWW", "NOV", "RCL", "SYMC", "MU", "AA", "HST", "AWK", "TSCO", "FOX", "XLNX", "HOT", "LRCX", "FCX", "DVA", "COL", "HRL", "CHD", "VRSK", "CTXS", "AEE", "MHK", "LH", "CFG", "AAP", "HBI", "MSI", "WDC", "AME", "KIM", "RSG", "WFM", "CPB", "CMS", "COH", "NWL", "MAT", "PFG", "WMB", "STX", "MKC", "KORS", "KLAC", "RF", "TSO", "MAC", "XL", "EXR", "WAT", "FRT", "L", "CCE", "LLTC", "KMX", "EMN", "UHS", "MLM", "CHRW", "XRX", "BBY", "DGX", "COG", "HRS", "MAS", "AKAM", "LNC", "MCHP", "DOV", "SRCL", "WU", "DHI", "MOS", "WRK", "UDR", "CINF", "SCG", "BLL", "HOG", "SLG", "KEY", "LLL", "TXT", "KSS", "SEE", "KSU", "JNPR", "MRO", "ARG", "EQT", "PNR", "EXPD", "CA", "GT", "SIG", "CPGX", "WYN", "HAS", "ENDP", "IFF", "XEC", "SNA", "IPG", "VRSN", "CNP", "BBBY", "AMG", "LEN", "CF", "BWA", "TIF", "CBG", "NTAP", "MNK", "HBAN", "CTAS", "GAS", "UNM", "VAR", "JWN", "PNW", "DRI", "NDAQ", "TSS", "JBHT", "AES", "ETFC", "FLR", "CVC", "NI", "FFIV", "PVH", "TRIP", "DISCK", "XYL", "GPS", "WYNN", "ADT", "HP", "CMA", "HRB", "TMK", "TE", "AVY", "QRVO", "FTI", "LEG", "SPLS", "FTR", "AIV", "IRM", "SNI", "ALLE", "FLS", "PHM", "OKE", "RL", "HAR", "RHI", "URI", "POM", "TGNA", "PKI", "FMC", "FSLR", "RRC", "AIZ", "JEC", "LUK", "NFX", "ZION", "PBCT", "GRMN", "FLIR", "NWSA", "NAVI", "NRG", "DISCA", "PBI", "AN", "MUR", "RIG", "PWR", "PDCO", "LM", "TDC", "DNB", "CSRA", "GME", "R", "SWN", "URBN", "THC", "ESV", "CHK", "OI", "DO", "NWS", "GMCR"];

